import { WordModel } from '@models';
import { logger } from '@utils';
import { generateId } from '@utils';

/**
 * Migration: Add Nigerian-focused words across all categories
 * Enhances the word database with words relevant to Nigerian users
 */

interface WordEntry {
  word: string;
  category: string;
  difficulty?: number;
  aliases?: string[];
}

const nigerianWords: WordEntry[] = [
  // NIGERIAN NAMES (Yoruba, Igbo, Hausa, and popular Nigerian names)
  { word: 'abayomi', category: 'name', difficulty: 1 },
  { word: 'abimbola', category: 'name', difficulty: 1, aliases: ['bimbo'] },
  { word: 'adebayo', category: 'name', difficulty: 1 },
  { word: 'adebola', category: 'name', difficulty: 1 },
  { word: 'adedayo', category: 'name', difficulty: 1 },
  { word: 'adedoyin', category: 'name', difficulty: 1 },
  { word: 'adegoke', category: 'name', difficulty: 1 },
  { word: 'adeleke', category: 'name', difficulty: 1 },
  { word: 'ademola', category: 'name', difficulty: 1 },
  { word: 'adeola', category: 'name', difficulty: 1 },
  { word: 'adesanya', category: 'name', difficulty: 1 },
  { word: 'adetola', category: 'name', difficulty: 1 },
  { word: 'adetayo', category: 'name', difficulty: 1 },
  { word: 'adeyemi', category: 'name', difficulty: 1 },
  { word: 'aduke', category: 'name', difficulty: 1 },
  { word: 'afolabi', category: 'name', difficulty: 1 },
  { word: 'afolake', category: 'name', difficulty: 1 },
  { word: 'aisha', category: 'name', difficulty: 1 },
  { word: 'ajayi', category: 'name', difficulty: 1 },
  { word: 'akeem', category: 'name', difficulty: 1 },
  { word: 'akindele', category: 'name', difficulty: 1 },
  { word: 'akinwale', category: 'name', difficulty: 1 },
  { word: 'akinwumi', category: 'name', difficulty: 1 },
  { word: 'akinyemi', category: 'name', difficulty: 1 },
  { word: 'amadi', category: 'name', difficulty: 1 },
  { word: 'amaka', category: 'name', difficulty: 1 },
  { word: 'aminu', category: 'name', difficulty: 1 },
  { word: 'aminat', category: 'name', difficulty: 1 },
  { word: 'anuoluwapo', category: 'name', difficulty: 2 },
  { word: 'ayodele', category: 'name', difficulty: 1 },
  { word: 'ayomide', category: 'name', difficulty: 1 },
  { word: 'ayotunde', category: 'name', difficulty: 1 },
  { word: 'babajide', category: 'name', difficulty: 1 },
  { word: 'babatunde', category: 'name', difficulty: 1 },
  { word: 'bolaji', category: 'name', difficulty: 1 },
  { word: 'bolanle', category: 'name', difficulty: 1 },
  { word: 'busayo', category: 'name', difficulty: 1 },
  { word: 'chidi', category: 'name', difficulty: 1 },
  { word: 'chika', category: 'name', difficulty: 1 },
  { word: 'chidera', category: 'name', difficulty: 1 },
  { word: 'chinedu', category: 'name', difficulty: 1 },
  { word: 'chinonso', category: 'name', difficulty: 1 },
  { word: 'chioma', category: 'name', difficulty: 1 },
  { word: 'damilare', category: 'name', difficulty: 1 },
  { word: 'damilola', category: 'name', difficulty: 1 },
  { word: 'dayo', category: 'name', difficulty: 1 },
  { word: 'ebuka', category: 'name', difficulty: 1 },
  { word: 'ejiro', category: 'name', difficulty: 1 },
  { word: 'emeka', category: 'name', difficulty: 1 },
  { word: 'ese', category: 'name', difficulty: 1 },
  { word: 'farida', category: 'name', difficulty: 1 },
  { word: 'fatima', category: 'name', difficulty: 1 },
  { word: 'folake', category: 'name', difficulty: 1 },
  { word: 'folashade', category: 'name', difficulty: 1 },
  { word: 'funke', category: 'name', difficulty: 1 },
  { word: 'funmilayo', category: 'name', difficulty: 1 },
  { word: 'gbenga', category: 'name', difficulty: 1 },
  { word: 'habib', category: 'name', difficulty: 1 },
  { word: 'halima', category: 'name', difficulty: 1 },
  { word: 'hauwa', category: 'name', difficulty: 1 },
  { word: 'ibukun', category: 'name', difficulty: 1 },
  { word: 'idowu', category: 'name', difficulty: 1 },
  { word: 'ifeanyi', category: 'name', difficulty: 1 },
  { word: 'ifeoma', category: 'name', difficulty: 1 },
  { word: 'ikechukwu', category: 'name', difficulty: 1 },
  { word: 'ikeoluwa', category: 'name', difficulty: 1 },
  { word: 'ireti', category: 'name', difficulty: 1 },
  { word: 'ismail', category: 'name', difficulty: 1 },
  { word: 'jibola', category: 'name', difficulty: 1 },
  { word: 'jumoke', category: 'name', difficulty: 1 },
  { word: 'kafilat', category: 'name', difficulty: 1 },
  { word: 'kehinde', category: 'name', difficulty: 1 },
  { word: 'kemi', category: 'name', difficulty: 1 },
  { word: 'kunle', category: 'name', difficulty: 1 },
  { word: 'latifa', category: 'name', difficulty: 1 },
  { word: 'mojisola', category: 'name', difficulty: 1 },
  { word: 'motunrayo', category: 'name', difficulty: 1 },
  { word: 'musa', category: 'name', difficulty: 1 },
  { word: 'ngozi', category: 'name', difficulty: 1 },
  { word: 'nkechi', category: 'name', difficulty: 1 },
  { word: 'nnamdi', category: 'name', difficulty: 1 },
  { word: 'obinna', category: 'name', difficulty: 1 },
  { word: 'odunayo', category: 'name', difficulty: 1 },
  { word: 'ogechi', category: 'name', difficulty: 1 },
  { word: 'oladele', category: 'name', difficulty: 1 },
  { word: 'oladipo', category: 'name', difficulty: 1 },
  { word: 'olamide', category: 'name', difficulty: 1 },
  { word: 'olaniyan', category: 'name', difficulty: 1 },
  { word: 'olawale', category: 'name', difficulty: 1 },
  { word: 'olayinka', category: 'name', difficulty: 1 },
  { word: 'olubunmi', category: 'name', difficulty: 1 },
  { word: 'olufemi', category: 'name', difficulty: 1 },
  { word: 'olumide', category: 'name', difficulty: 1 },
  { word: 'olusegun', category: 'name', difficulty: 1 },
  { word: 'oluseyi', category: 'name', difficulty: 1 },
  { word: 'olushola', category: 'name', difficulty: 1 },
  { word: 'olutola', category: 'name', difficulty: 1 },
  { word: 'oluwaseun', category: 'name', difficulty: 1 },
  { word: 'oluwaseyi', category: 'name', difficulty: 1 },
  { word: 'oluwatobiloba', category: 'name', difficulty: 2, aliases: ['tobi'] },
  { word: 'oluwatomilola', category: 'name', difficulty: 2, aliases: ['tomi'] },
  { word: 'oluwatoyosi', category: 'name', difficulty: 2 },
  { word: 'omolara', category: 'name', difficulty: 1 },
  { word: 'omowunmi', category: 'name', difficulty: 1 },
  { word: 'oyindamola', category: 'name', difficulty: 1 },
  { word: 'rasheed', category: 'name', difficulty: 1 },
  { word: 'rashida', category: 'name', difficulty: 1 },
  { word: 'segun', category: 'name', difficulty: 1 },
  { word: 'sade', category: 'name', difficulty: 1 },
  { word: 'shola', category: 'name', difficulty: 1 },
  { word: 'sulaimon', category: 'name', difficulty: 1 },
  { word: 'taiwo', category: 'name', difficulty: 1 },
  { word: 'taiye', category: 'name', difficulty: 1 },
  { word: 'temitope', category: 'name', difficulty: 1, aliases: ['tope'] },
  { word: 'teniola', category: 'name', difficulty: 1, aliases: ['teni'] },
  { word: 'titilayo', category: 'name', difficulty: 1, aliases: ['titi'] },
  { word: 'tolu', category: 'name', difficulty: 1 },
  { word: 'tolulope', category: 'name', difficulty: 1 },
  { word: 'uche', category: 'name', difficulty: 1 },
  { word: 'usman', category: 'name', difficulty: 1 },
  { word: 'wasiu', category: 'name', difficulty: 1 },
  { word: 'yemi', category: 'name', difficulty: 1 },
  { word: 'yetunde', category: 'name', difficulty: 1 },
  { word: 'yinka', category: 'name', difficulty: 1 },
  { word: 'zainab', category: 'name', difficulty: 1 },

  // NIGERIAN CITIES AND PLACES
  { word: 'abuja', category: 'city', difficulty: 1, aliases: ['fct'] },
  { word: 'lagos', category: 'city', difficulty: 1 },
  { word: 'kano', category: 'city', difficulty: 1 },
  { word: 'ibadan', category: 'city', difficulty: 1 },
  { word: 'kaduna', category: 'city', difficulty: 1 },
  { word: 'port harcourt', category: 'city', difficulty: 1, aliases: ['ph', 'portharcourt'] },
  { word: 'benin city', category: 'city', difficulty: 1, aliases: ['benin'] },
  { word: 'maiduguri', category: 'city', difficulty: 1 },
  { word: 'zaria', category: 'city', difficulty: 1 },
  { word: 'aba', category: 'city', difficulty: 1 },
  { word: 'jos', category: 'city', difficulty: 1 },
  { word: 'ilorin', category: 'city', difficulty: 1 },
  { word: 'oyo', category: 'city', difficulty: 1 },
  { word: 'enugu', category: 'city', difficulty: 1 },
  { word: 'abeokuta', category: 'city', difficulty: 1 },
  { word: 'abeoukuta', category: 'city', difficulty: 1 },
  { word: 'sokoto', category: 'city', difficulty: 1 },
  { word: 'onitsha', category: 'city', difficulty: 1 },
  { word: 'warri', category: 'city', difficulty: 1 },
  { word: 'ebute metta', category: 'city', difficulty: 2, aliases: ['ebute-metta'] },
  { word: 'ikeja', category: 'city', difficulty: 1 },
  { word: 'yaba', category: 'city', difficulty: 1 },
  { word: 'surulere', category: 'city', difficulty: 1 },
  { word: 'lekki', category: 'city', difficulty: 1 },
  { word: 'ajah', category: 'city', difficulty: 1 },
  { word: 'victoria island', category: 'city', difficulty: 1, aliases: ['vi'] },
  { word: 'ikoyi', category: 'city', difficulty: 1 },
  { word: 'festac', category: 'city', difficulty: 1 },
  { word: 'calabar', category: 'city', difficulty: 1 },
  { word: 'uyo', category: 'city', difficulty: 1 },
  { word: 'akure', category: 'city', difficulty: 1 },
  { word: 'ado ekiti', category: 'city', difficulty: 1, aliases: ['ado-ekiti'] },
  { word: 'bauchi', category: 'city', difficulty: 1 },
  { word: 'gombe', category: 'city', difficulty: 1 },
  { word: 'dutse', category: 'city', difficulty: 1 },
  { word: 'lafia', category: 'city', difficulty: 1 },
  { word: 'lokoja', category: 'city', difficulty: 1 },
  { word: 'makurdi', category: 'city', difficulty: 1 },
  { word: 'minna', category: 'city', difficulty: 1 },
  { word: 'osogbo', category: 'city', difficulty: 1 },
  { word: 'owerri', category: 'city', difficulty: 1 },
  { word: 'umuahia', category: 'city', difficulty: 1 },
  { word: 'yenagoa', category: 'city', difficulty: 1 },
  { word: 'asaba', category: 'city', difficulty: 1 },
  { word: 'awka', category: 'city', difficulty: 1 },
  { word: 'abakaliki', category: 'city', difficulty: 1 },
  { word: 'jalingo', category: 'city', difficulty: 1 },
  { word: 'damaturu', category: 'city', difficulty: 1 },
  { word: 'birnin kebbi', category: 'city', difficulty: 1 },
  { word: 'gusau', category: 'city', difficulty: 1 },
  { word: 'ondo', category: 'city', difficulty: 1 },
  { word: 'ogbomosho', category: 'city', difficulty: 1 },
  { word: 'ile-ife', category: 'city', difficulty: 1, aliases: ['ife'] },
  { word: 'ilesha', category: 'city', difficulty: 1 },
  { word: 'ede', category: 'city', difficulty: 1 },
  { word: 'ijebu ode', category: 'city', difficulty: 1, aliases: ['ijebu-ode'] },
  { word: 'ota', category: 'city', difficulty: 1 },
  { word: 'sango ota', category: 'city', difficulty: 1, aliases: ['sango'] },
  { word: 'badagry', category: 'city', difficulty: 1 },
  { word: 'epe', category: 'city', difficulty: 1 },
  { word: 'ikorodu', category: 'city', difficulty: 1 },
  { word: 'agege', category: 'city', difficulty: 1 },
  { word: 'mushin', category: 'city', difficulty: 1 },
  { word: 'nsukka', category: 'city', difficulty: 1 },
  { word: 'sapele', category: 'city', difficulty: 1 },
  { word: 'ughelli', category: 'city', difficulty: 1 },

  // NIGERIAN PLACES/LANDMARKS
  { word: 'aso rock', category: 'place', difficulty: 1, aliases: ['asorock'] },
  { word: 'bar beach', category: 'place', difficulty: 1 },
  { word: 'third mainland bridge', category: 'place', difficulty: 2 },
  { word: 'national theatre', category: 'place', difficulty: 1 },
  { word: 'tafawa balewa square', category: 'place', difficulty: 2, aliases: ['tbs'] },
  { word: 'olumo rock', category: 'place', difficulty: 1 },
  { word: 'zuma rock', category: 'place', difficulty: 1 },
  { word: 'yankari national park', category: 'place', difficulty: 2 },
  { word: 'obudu cattle ranch', category: 'place', difficulty: 2 },
  { word: 'idanre hills', category: 'place', difficulty: 2 },
  { word: 'ikogosi warm springs', category: 'place', difficulty: 2 },
  { word: 'nike lake', category: 'place', difficulty: 1 },
  { word: 'niger delta', category: 'place', difficulty: 1 },
  { word: 'sambisa forest', category: 'place', difficulty: 2 },
  { word: 'chad basin', category: 'place', difficulty: 2 },
  { word: 'niger river', category: 'place', difficulty: 1 },
  { word: 'benue river', category: 'place', difficulty: 1 },
  { word: 'computer village', category: 'place', difficulty: 1 },
  { word: 'ogere', category: 'place', difficulty: 1 },

  // NIGERIAN FOOD
  { word: 'jollof rice', category: 'food', difficulty: 1, aliases: ['jollof'] },
  { word: 'suya', category: 'food', difficulty: 1 },
  { word: 'pounded yam', category: 'food', difficulty: 1, aliases: ['poundo'] },
  { word: 'egusi soup', category: 'food', difficulty: 1, aliases: ['egusi'] },
  { word: 'efo riro', category: 'food', difficulty: 1 },
  { word: 'eba', category: 'food', difficulty: 1, aliases: ['garri'] },
  { word: 'amala', category: 'food', difficulty: 1 },
  { word: 'fufu', category: 'food', difficulty: 1 },
  { word: 'ofada rice', category: 'food', difficulty: 2, aliases: ['ofada'] },
  { word: 'akara', category: 'food', difficulty: 1 },
  { word: 'moi moi', category: 'food', difficulty: 1, aliases: ['moimoi'] },
  { word: 'dodo', category: 'food', difficulty: 1 },
  { word: 'plantain', category: 'food', difficulty: 1 },
  { word: 'chin chin', category: 'food', difficulty: 1, aliases: ['chinchin'] },
  { word: 'puff puff', category: 'food', difficulty: 1, aliases: ['puffpuff'] },
  { word: 'ogbono soup', category: 'food', difficulty: 1, aliases: ['ogbono'] },
  { word: 'okro soup', category: 'food', difficulty: 1, aliases: ['okra'] },
  { word: 'bitterleaf soup', category: 'food', difficulty: 2 },
  { word: 'edikang ikong', category: 'food', difficulty: 2 },
  { word: 'afang soup', category: 'food', difficulty: 1, aliases: ['afang'] },
  { word: 'oha soup', category: 'food', difficulty: 1, aliases: ['ora', 'ofe oha'] },
  { word: 'nsala soup', category: 'food', difficulty: 2, aliases: ['white soup'] },
  { word: 'pepper soup', category: 'food', difficulty: 1 },
  { word: 'nkwobi', category: 'food', difficulty: 1 },
  { word: 'isi ewu', category: 'food', difficulty: 2 },
  { word: 'gizdodo', category: 'food', difficulty: 1 },
  { word: 'asun', category: 'food', difficulty: 1 },
  { word: 'kilishi', category: 'food', difficulty: 1 },
  { word: 'masa', category: 'food', difficulty: 1 },
  { word: 'tuwo shinkafa', category: 'food', difficulty: 2, aliases: ['tuwo'] },
  { word: 'miyan kuka', category: 'food', difficulty: 2 },
  { word: 'dan wake', category: 'food', difficulty: 2 },
  { word: 'fura da nono', category: 'food', difficulty: 2, aliases: ['fura'] },
  { word: 'kunun aya', category: 'food', difficulty: 2, aliases: ['kunun'] },
  { word: 'zobo', category: 'food', difficulty: 1 },
  { word: 'chapman', category: 'food', difficulty: 1 },
  { word: 'agidi', category: 'food', difficulty: 1 },
  { word: 'abacha', category: 'food', difficulty: 1 },
  { word: 'ugba', category: 'food', difficulty: 1 },
  { word: 'boli', category: 'food', difficulty: 1 },
  { word: 'yam porridge', category: 'food', difficulty: 1, aliases: ['asaro'] },
  { word: 'beans porridge', category: 'food', difficulty: 1 },
  { word: 'ewa agoyin', category: 'food', difficulty: 1 },
  { word: 'ofada stew', category: 'food', difficulty: 2 },
  { word: 'ayamase', category: 'food', difficulty: 1, aliases: ['designer stew'] },
  { word: 'ewedu', category: 'food', difficulty: 1 },
  { word: 'gbegiri', category: 'food', difficulty: 1 },
  { word: 'kokoro', category: 'food', difficulty: 1 },
  { word: 'gala', category: 'food', difficulty: 1 },
  { word: 'meat pie', category: 'food', difficulty: 1 },
  { word: 'buns', category: 'food', difficulty: 1 },

  // NIGERIAN COMPANIES
  { word: 'dangote', category: 'company', difficulty: 1 },
  { word: 'globacom', category: 'company', difficulty: 1, aliases: ['glo'] },
  { word: 'mtn', category: 'company', difficulty: 1 },
  { word: 'airtel', category: 'company', difficulty: 1 },
  { word: '9mobile', category: 'company', difficulty: 1 },
  { word: 'gtbank', category: 'company', difficulty: 1, aliases: ['guaranty trust bank'] },
  { word: 'zenith bank', category: 'company', difficulty: 1, aliases: ['zenith'] },
  { word: 'access bank', category: 'company', difficulty: 1, aliases: ['access'] },
  { word: 'first bank', category: 'company', difficulty: 1, aliases: ['firstbank'] },
  { word: 'uba', category: 'company', difficulty: 1, aliases: ['united bank for africa'] },
  { word: 'union bank', category: 'company', difficulty: 1 },
  { word: 'fidelity bank', category: 'company', difficulty: 1, aliases: ['fidelity'] },
  { word: 'stanbic ibtc', category: 'company', difficulty: 1, aliases: ['stanbic'] },
  { word: 'sterling bank', category: 'company', difficulty: 1, aliases: ['sterling'] },
  { word: 'wema bank', category: 'company', difficulty: 1, aliases: ['wema'] },
  { word: 'polaris bank', category: 'company', difficulty: 1, aliases: ['polaris'] },
  { word: 'ecobank', category: 'company', difficulty: 1 },
  { word: 'kuda bank', category: 'company', difficulty: 1, aliases: ['kuda'] },
  { word: 'opay', category: 'company', difficulty: 1 },
  { word: 'palmpay', category: 'company', difficulty: 1 },
  { word: 'paystack', category: 'company', difficulty: 1 },
  { word: 'flutterwave', category: 'company', difficulty: 1 },
  { word: 'interswitch', category: 'company', difficulty: 1 },
  { word: 'jumia', category: 'company', difficulty: 1 },
  { word: 'konga', category: 'company', difficulty: 1 },
  { word: 'jiji', category: 'company', difficulty: 1 },
  { word: 'bolt', category: 'company', difficulty: 1 },
  { word: 'uber', category: 'company', difficulty: 1 },
  { word: 'innoson', category: 'company', difficulty: 1 },
  { word: 'shoprite', category: 'company', difficulty: 1 },
  { word: 'spar', category: 'company', difficulty: 1 },
  { word: 'nnpc', category: 'company', difficulty: 1 },
  { word: 'shell', category: 'company', difficulty: 1 },
  { word: 'chevron', category: 'company', difficulty: 1 },
  { word: 'total', category: 'company', difficulty: 1 },
  { word: 'mobil', category: 'company', difficulty: 1 },
  { word: 'conoil', category: 'company', difficulty: 1 },
  { word: 'oando', category: 'company', difficulty: 1 },
  { word: 'ntel', category: 'company', difficulty: 1 },
  { word: 'slot', category: 'company', difficulty: 1 },
  { word: 'yudala', category: 'company', difficulty: 1 },
  { word: 'chickenrepublic', category: 'company', difficulty: 1, aliases: ['chicken republic'] },
  { word: 'sweet sensation', category: 'company', difficulty: 1 },
  { word: 'mr biggs', category: 'company', difficulty: 1, aliases: ['mr. biggs'] },
  { word: 'coldstone', category: 'company', difficulty: 1 },
  { word: 'filmhouse', category: 'company', difficulty: 1 },
  { word: 'silverbird', category: 'company', difficulty: 1 },
  { word: 'arik air', category: 'company', difficulty: 1, aliases: ['arik'] },
  { word: 'air peace', category: 'company', difficulty: 1 },
  { word: 'dana air', category: 'company', difficulty: 1, aliases: ['dana'] },
  { word: 'medview', category: 'company', difficulty: 1 },
  { word: 'andela', category: 'company', difficulty: 1 },
  { word: 'piggyvest', category: 'company', difficulty: 1 },
  { word: 'cowrywise', category: 'company', difficulty: 1 },

  // NIGERIAN APPS
  { word: 'opay', category: 'app', difficulty: 1 },
  { word: 'palmpay', category: 'app', difficulty: 1 },
  { word: 'kuda', category: 'app', difficulty: 1 },
  { word: 'piggyvest', category: 'app', difficulty: 1 },
  { word: 'cowrywise', category: 'app', difficulty: 1 },
  { word: 'carbon', category: 'app', difficulty: 1 },
  { word: 'fairmoney', category: 'app', difficulty: 1 },
  { word: 'paylater', category: 'app', difficulty: 1 },
  { word: 'branch', category: 'app', difficulty: 1 },
  { word: 'renmoney', category: 'app', difficulty: 1 },
  { word: 'quickteller', category: 'app', difficulty: 1 },
  { word: 'jumia', category: 'app', difficulty: 1 },
  { word: 'konga', category: 'app', difficulty: 1 },
  { word: 'jiji', category: 'app', difficulty: 1 },
  { word: 'bolt', category: 'app', difficulty: 1 },
  { word: 'gokada', category: 'app', difficulty: 1 },
  { word: 'max', category: 'app', difficulty: 1 },
  { word: 'safeboda', category: 'app', difficulty: 1 },
  { word: 'chowdeck', category: 'app', difficulty: 1 },
  { word: 'glovo', category: 'app', difficulty: 1 },
  { word: 'sendstack', category: 'app', difficulty: 1 },
  { word: 'audiomack', category: 'app', difficulty: 1 },
  { word: 'boomplay', category: 'app', difficulty: 1 },
  { word: 'showmax', category: 'app', difficulty: 1 },
  { word: 'iroko tv', category: 'app', difficulty: 1, aliases: ['irokotv'] },
  { word: 'naijapals', category: 'app', difficulty: 1 },
  { word: 'gidi', category: 'app', difficulty: 1 },
  { word: 'mygov', category: 'app', difficulty: 1 },
  { word: 'remita', category: 'app', difficulty: 1 },

  // NIGERIAN LANGUAGES
  { word: 'yoruba', category: 'language', difficulty: 1 },
  { word: 'igbo', category: 'language', difficulty: 1 },
  { word: 'hausa', category: 'language', difficulty: 1 },
  { word: 'pidgin', category: 'language', difficulty: 1, aliases: ['nigerian pidgin'] },
  { word: 'efik', category: 'language', difficulty: 1 },
  { word: 'ibibio', category: 'language', difficulty: 1 },
  { word: 'edo', category: 'language', difficulty: 1 },
  { word: 'fulfulde', category: 'language', difficulty: 1, aliases: ['fulani'] },
  { word: 'kanuri', category: 'language', difficulty: 1 },
  { word: 'tiv', category: 'language', difficulty: 1 },
  { word: 'ijaw', category: 'language', difficulty: 1, aliases: ['izon'] },
  { word: 'urhobo', category: 'language', difficulty: 1 },
  { word: 'isoko', category: 'language', difficulty: 1 },
  { word: 'esan', category: 'language', difficulty: 1 },
  { word: 'ebira', category: 'language', difficulty: 1 },
  { word: 'nupe', category: 'language', difficulty: 1 },
  { word: 'gwari', category: 'language', difficulty: 1 },
  { word: 'idoma', category: 'language', difficulty: 1 },
  { word: 'igala', category: 'language', difficulty: 1 },
  { word: 'itsekiri', category: 'language', difficulty: 1 },
  { word: 'berom', category: 'language', difficulty: 1 },
  { word: 'angas', category: 'language', difficulty: 1 },

  // AFRICAN ANIMALS (common in Nigeria)
  { word: 'pangolin', category: 'animal', difficulty: 2 },
  { word: 'bushbaby', category: 'animal', difficulty: 1 },
  { word: 'civet', category: 'animal', difficulty: 2 },
  { word: 'manatee', category: 'animal', difficulty: 1 },
  { word: 'cane rat', category: 'animal', difficulty: 1, aliases: ['grasscutter'] },

  // NIGERIAN CURRENCY
  { word: 'naira', category: 'currency', difficulty: 1 },
  { word: 'kobo', category: 'currency', difficulty: 1 },

  // NIGERIAN CARS (locally assembled/popular)
  { word: 'innoson', category: 'car', difficulty: 1 },
  { word: 'peugeot 504', category: 'car', difficulty: 1, aliases: ['504'] },
  { word: 'volkswagen beetle', category: 'car', difficulty: 1, aliases: ['ijapa'] },
  { word: 'toyota camry', category: 'car', difficulty: 1, aliases: ['camry'] },
  { word: 'toyota corolla', category: 'car', difficulty: 1, aliases: ['corolla'] },
  { word: 'honda accord', category: 'car', difficulty: 1, aliases: ['accord'] },
  { word: 'honda civic', category: 'car', difficulty: 1, aliases: ['civic'] },
  { word: 'lexus', category: 'car', difficulty: 1 },
  { word: 'sienna', category: 'car', difficulty: 1 },
  { word: 'highlander', category: 'car', difficulty: 1 },
  { word: 'danfo', category: 'car', difficulty: 1 },
  { word: 'keke napep', category: 'car', difficulty: 1, aliases: ['keke'] },
  { word: 'okada', category: 'car', difficulty: 1 },

  // COLORS (Nigerian context - include common ones)
  { word: 'green', category: 'color', difficulty: 1 },
  { word: 'white', category: 'color', difficulty: 1 },
];

export async function up(): Promise<void> {
  logger.info('Starting migration: Add Nigerian-focused words');

  let inserted = 0;
  let skipped = 0;
  let errors = 0;

  for (const entry of nigerianWords) {
    try {
      const startsWith = entry.word.charAt(0).toLowerCase();

      // Check if word already exists
      const existingWord = await WordModel.findOne({
        word: entry.word,
        category: entry.category,
      });

      if (existingWord) {
        skipped++;
        logger.debug(`Word "${entry.word}" already exists, skipping`);
        continue;
      }

      // Insert new word
      await WordModel.create({
        id: generateId(16, 'WORD'),
        word: entry.word,
        category: entry.category,
        startsWith: startsWith,
        difficulty: entry.difficulty || 1,
        aliases: entry.aliases || [],
        popularity: 0,
        validationCount: 0,
        contestCount: 0,
        addedBy: 'migration',
        isUserSubmitted: false,
        isReviewed: true,
        isApproved: true,
      });

      inserted++;
      logger.debug(`Inserted word: "${entry.word}" (${entry.category})`);
    } catch (error: any) {
      errors++;
      logger.error(`Error inserting word "${entry.word}"`, error);
    }
  }

  logger.info(`Migration complete: ${inserted} inserted, ${skipped} skipped, ${errors} errors`);
  logger.info(`Summary by category:`);

  const categoryCounts: Record<string, number> = {};
  nigerianWords.forEach(word => {
    categoryCounts[word.category] = (categoryCounts[word.category] || 0) + 1;
  });

  Object.entries(categoryCounts).forEach(([category, count]) => {
    logger.info(`  ${category}: ${count} words`);
  });
}

export async function down(): Promise<void> {
  logger.info('Rolling back migration: Remove Nigerian-focused words');

  const wordsToRemove = nigerianWords.map(w => w.word);

  const result = await WordModel.deleteMany({
    word: { $in: wordsToRemove },
    addedBy: 'migration',
  });

  logger.info(`Rollback complete: ${result.deletedCount} documents deleted`);
}
